vpc-name      = "Nida-vpc"
igw-name      = "Nida-igw"
subnet-name   = "Nida-subnet"
rt-name       = "Nida-route-table"
sg-name       = "Nida-sg"
instance-name = "Nida-server"
key-name      = "Reddit"
iam-role      = "Nida-iam-role"
